import type { MDXComponents } from 'mdx/types'
 
export function useMDXComponents(components: MDXComponents): MDXComponents {
  return {
    // These are just examples generated by copilot, this should be changed to reflect our actual design style
    h1: (props) => <h1 style={{ color: 'darkblue', fontSize: '2.5rem' }} {...props} />,
    p: (props) => <p style={{ lineHeight: '1.6', fontSize: '1rem' }} {...props} />,
    a: (props) => <a style={{ color: 'teal', textDecoration: 'underline' }} {...props} />,
    ...components,
  }
}