const countries = {
  Afghanistan: "afghanistan",
  Albania: "albania",
  Algeria: "algeria",
  "American Samoa": "american samoa",
  Andorra: "andorra",
  Angola: "angola",
  Anguilla: "anguilla",
  Antarctica: "antarctica",
  "Antigua and Barbuda": "antigua and barbuda",
  Argentina: "argentina",
  Armenia: "armenia",
  Aruba: "aruba",
  Australia: "australia",
  Austria: "austria",
  Azerbaijan: "azerbaijan",
  Bahamas: "bahamas",
  Bahrain: "bahrain",
  Bangladesh: "bangladesh",
  Barbados: "barbados",
  Belarus: "belarus",
  Belgium: "belgium",
  Belize: "belize",
  Benin: "benin",
  Bermuda: "bermuda",
  Bhutan: "bhutan",
  Bolivia: "bolivia",
  Bonaire: "bonaire",
  "Bosnia and Herzegovina": "bosnia and herzegovina",
  Botswana: "botswana",
  "Bouvet Island": "bouvet island",
  Brazil: "brazil",
  "British Indian Ocean Territory": "british indian ocean territory",
  "Brunei Darussalam": "brunei darussalam",
  Bulgaria: "bulgaria",
  "Burkina Faso": "burkina faso",
  Burundi: "burundi",
  Cambodia: "cambodia",
  Cameroon: "cameroon",
  Canada: "canada",
  "Cape Verde": "cape verde",
  "Cayman Islands": "cayman islands",
  "Central African Republic": "central african republic",
  Chad: "chad",
  Chile: "chile",
  China: "china",
  "Christmas Island": "christmas island",
  "Cocos (Keeling) Islands": "cocos (keeling) islands",
  Colombia: "colombia",
  Comoros: "comoros",
  Congo: "congo",
  "Congo, The Democratic Republic of the":
    "congo, the democratic republic of the",
  "Cook Islands": "cook islands",
  "Costa Rica": "costa rica",
  "Cote d'Ivoire": "cote d'ivoire",
  Croatia: "croatia",
  Cuba: "cuba",
  Curacao: "curacao",
  Cyprus: "cyprus",
  "Czech Republic": "czech republic",
  Denmark: "denmark",
  Djibouti: "djibouti",
  Dominica: "dominica",
  "Dominican Republic": "dominican republic",
  Ecuador: "ecuador",
  Egypt: "egypt",
  "El Salvador": "el salvador",
  "Equatorial Guinea": "equatorial guinea",
  Eritrea: "eritrea",
  Estonia: "estonia",
  Eswatini: "eswatini",
  Ethiopia: "ethiopia",
  "Falkland Islands (Malvinas)": "falkland islands (malvinas)",
  "Faroe Islands": "faroe islands",
  Fiji: "fiji",
  Finland: "finland",
  France: "france",
  "French Guiana": "french guiana",
  "French Polynesia": "french polynesia",
  "French Southern Territories": "french southern territories",
  Gabon: "gabon",
  Gambia: "gambia",
  Georgia: "georgia",
  Germany: "germany",
  Ghana: "ghana",
  Gibraltar: "gibraltar",
  Greece: "greece",
  Greenland: "greenland",
  Grenada: "grenada",
  Guadeloupe: "guadeloupe",
  Guam: "guam",
  Guatemala: "guatemala",
  Guernsey: "guernsey",
  Guinea: "guinea",
  "Guinea-Bissau": "guinea-bissau",
  Guyana: "guyana",
  Haiti: "haiti",
  "Heard Island and Mcdonald Islands": "heard island and mcdonald islands",
  "Holy See (Vatican City State)": "holy see (vatican city state)",
  Honduras: "honduras",
  "Hong Kong": "hong kong",
  Hungary: "hungary",
  Iceland: "iceland",
  India: "india",
  Indonesia: "indonesia",
  "Iran, Islamic Republic of": "iran, islamic republic of",
  Iraq: "iraq",
  Ireland: "ireland",
  "Isle of Man": "isle of man",
  Israel: "israel",
  Italy: "italy",
  "Ivory Coast": "ivory coast",
  Jamaica: "jamaica",
  Japan: "japan",
  Jersey: "jersey",
  Jordan: "jordan",
  Kazakhstan: "kazakhstan",
  Kenya: "kenya",
  Kiribati: "kiribati",
  "Korea, Democratic People's Republic of":
    "korea, democratic people's republic of",
  "Korea, Republic of": "korea, republic of",
  Kuwait: "kuwait",
  Kyrgyzstan: "kyrgyzstan",
  "Lao People's Democratic Republic": "lao people's democratic republic",
  Laos: "laos",
  Latvia: "latvia",
  Lebanon: "lebanon",
  Lesotho: "lesotho",
  Liberia: "liberia",
  "Libyan Arab Jamahiriya": "libyan arab jamahiriya",
  Liechtenstein: "liechtenstein",
  Lithuania: "lithuania",
  Luxembourg: "luxembourg",
  Macao: "macao",
  "Macedonia, The Republic of North": "macedonia, the republic of north",
  Madagascar: "madagascar",
  Malawi: "malawi",
  Malaysia: "malaysia",
  Maldives: "maldives",
  Mali: "mali",
  Malta: "malta",
  "Marshall Islands": "marshall islands",
  Martinique: "martinique",
  Mauritania: "mauritania",
  Mauritius: "mauritius",
  Mayotte: "mayotte",
  Mexico: "mexico",
  "Micronesia, Federated States of": "micronesia, federated states of",
  "Moldova, Republic of": "moldova, republic of",
  Monaco: "monaco",
  Mongolia: "mongolia",
  Montenegro: "montenegro",
  Montserrat: "montserrat",
  Morocco: "morocco",
  Mozambique: "mozambique",
  Myanmar: "myanmar",
  Namibia: "namibia",
  Nauru: "nauru",
  Nepal: "nepal",
  Netherlands: "netherlands",
  "Netherlands Antilles": "netherlands antilles",
  "New Caledonia": "new caledonia",
  "New Zealand": "new zealand",
  Nicaragua: "nicaragua",
  Niger: "niger",
  Nigeria: "nigeria",
  Niue: "niue",
  "Norfolk Island": "norfolk island",
  "Northern Mariana Islands": "northern mariana islands",
  Norway: "norway",
  Oman: "oman",
  Pakistan: "pakistan",
  Palau: "palau",
  "Palestinian Territory, Occupied": "palestinian territory, occupied",
  Panama: "panama",
  "Papua New Guinea": "papua new guinea",
  Paraguay: "paraguay",
  Peru: "peru",
  Philippines: "philippines",
  Pitcairn: "pitcairn",
  Poland: "poland",
  Portugal: "portugal",
  "Puerto Rico": "puerto rico",
  Qatar: "qatar",
  Rwanda: "rwanda",
  Reunion: "reunion",
  Romania: "romania",
  "Russian Federation": "russian federation",
  "Saint Barthelemy": "saint barthelemy",
  "Saint Helena": "saint helena",
  "Saint Kitts and Nevis": "saint kitts and nevis",
  "Saint Lucia": "saint lucia",
  "Saint Martin": "saint martin",
  "Saint Pierre and Miquelon": "saint pierre and miquelon",
  "Saint Vincent and the Grenadines": "saint vincent and the grenadines",
  Samoa: "samoa",
  "San Marino": "san marino",
  "Sao Tome and Principe": "sao tome and principe",
  "Saudi Arabia": "saudi arabia",
  Senegal: "senegal",
  Serbia: "serbia",
  Seychelles: "seychelles",
  "Sierra Leone": "sierra leone",
  Singapore: "singapore",
  "Sint Maarten": "sint maarten",
  Slovakia: "slovakia",
  Slovenia: "slovenia",
  "Solomon Islands": "solomon islands",
  Somalia: "somalia",
  "South Africa": "south africa",
  "South Georgia and the South Sandwich Islands":
    "south georgia and the south sandwich islands",
  "South Sudan": "south sudan",
  Spain: "spain",
  "Sri Lanka": "sri lanka",
  Sudan: "sudan",
  Suriname: "suriname",
  "Svalbard and Jan Mayen": "svalbard and jan mayen",
  Swaziland: "swaziland",
  Sweden: "sweden",
  Switzerland: "switzerland",
  "Syrian Arab Republic": "syrian arab republic",
  Taiwan: "taiwan",
  Tajikistan: "tajikistan",
  "Tanzania, United Republic of": "tanzania, united republic of",
  Thailand: "thailand",
  "Timor-Leste": "timor-leste",
  Togo: "togo",
  Tokelau: "tokelau",
  Tonga: "tonga",
  "Trinidad and Tobago": "trinidad and tobago",
  Tunisia: "tunisia",
  Turkey: "turkey",
  Turkmenistan: "turkmenistan",
  "Turks and Caicos Islands": "turks and caicos islands",
  Tuvalu: "tuvalu",
  Uganda: "uganda",
  Ukraine: "ukraine",
  "United Arab Emirates": "united arab emirates",
  "United Kingdom": "united kingdom",
  "United States": "united states",
  "United States Minor Outlying Islands":
    "united states minor outlying islands",
  Uruguay: "uruguay",
  Uzbekistan: "uzbekistan",
  Vanuatu: "vanuatu",
  Venezuela: "venezuela",
  Vietnam: "vietnam",
  "Virgin Islands, British": "virgin islands, british",
  "Virgin Islands, U.S.": "virgin islands, u.s.",
  "Wallis and Futuna": "wallis and futuna",
  "Western Sahara": "western sahara",
  Yemen: "yemen",
  Zambia: "zambia",
  Zimbabwe: "zimbabwe",
  "Åland Islands": "åland islands",
};

export default countries;
